# -*- coding: utf-8 -*-
"""testySphincs_500.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kupW85d7Nbm4m9ssMdCVbuWm6d5LZOqf
"""

import pandas as pd
import matplotlib.pyplot as plt
import re
import os

def parse_simblock_log_to_sec(filename):
    """Parsuje logi SimBlock i oblicza średni czas propagacji w sekundach."""
    if not os.path.exists(filename):
        print(f"--- BRAK PLIKU: {filename} ---")
        return None

    with open(filename, 'r') as f:
        content = f.read()

    # Ulepszony regex: szuka od nagłówka bloku aż do napotkania kolejnego nagłówka lub końca pliku
    blocks = re.findall(r'simblock\.block\..*?Block@.*?:.*?\n(.*?)(?=\n\nsimblock\.block|\Z)', content, re.DOTALL)

    print(f"Plik: {os.path.basename(filename)} | Znaleziono bloków: {len(blocks)}")

    max_delays = []
    for block in blocks:
        timestamps = []
        for line in block.strip().split('\n'):
            parts = line.split(',')
            if len(parts) == 2:
                try:
                    timestamps.append(int(parts[1]))
                except ValueError:
                    continue

        if timestamps:
            # Różnica między ostatnim a pierwszym węzłem (ms -> s)
            delay_sec = (max(timestamps) - min(timestamps)) / 1000.0
            max_delays.append(delay_sec)

    return sum(max_delays) / len(max_delays) if max_delays else 0

# --- KONFIGURACJA ---
# Sprawdź dokładnie, czy nazwy plików w folderze /content/sample_data/ są identyczne!
files = {
    '10 N': '/content/sample_data/Sphincs_10N_4019000B.txt',
    '50 N': '/content/sample_data/Sphincs_50N_4019000B.txt',
    '100 N': '/content/sample_data/Sphincs_100N_4019000B.txt',
    '200 N': '/content/sample_data/Sphincs_200N_4019000B.txt',
    '500 N': '/content/sample_data/Sphincs_500N_4019000B.txt',
    '1000 N': '/content/sample_data/Sphincs_1000N_4019000B.txt',
    '2000 N': '/content/sample_data/Sphincs_2000N_4019000B.txt',
    '4000 N': '/content/sample_data/Sphincs_4000N_4019000B.txt'
}

results = []

for label, filename in files.items():
    avg_delay = parse_simblock_log_to_sec(filename)
    if avg_delay is not None:
        results.append({'Konfiguracja': label, 'Czas_s': round(avg_delay, 3)})

# Tworzenie DataFrame
df = pd.DataFrame(results)

# --- WYKRES ---
if not df.empty:
    plt.figure(figsize=(10, 6))
    bars = plt.bar(df['Konfiguracja'], df['Czas_s'], color='#3498db', alpha=0.8)

    # Dodanie wartości nad słupkami
    for bar in bars:
        yval = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, yval + (yval*0.01), f"{yval}s", ha='center', va='bottom', fontweight='bold')

    plt.title('Czas propagacji bloku (SPHINCS+)', fontsize=14)
    plt.ylabel('Średni czas [s]')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.savefig('porownanie_algorytmow_pqcSPHINCS_500.png')
    plt.show()
else:
    print("BŁĄD: Nie przetworzono żadnych danych. Sprawdź ścieżki do plików.")