# -*- coding: utf-8 -*-
"""Syrotki.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14BZCj_NN5j0Ia1AAizT3jYoswWwQwa8o
"""

import re
import matplotlib.pyplot as plt

def calculate_orphan_blocks(file_path):
    """
    Czyta plik logów i zlicza bloki, po których bezpośrednio następuje kolejny blok
    (czyli nie mają pod spodem żadnych transakcji/danych).
    """
    orphan_count = 0
    # Wyrażenie regularne szukające wzorca bloku
    block_pattern = re.compile(r"simblock\.block\.ProofOfWorkBlock@[a-f0-9]+:\d+", re.IGNORECASE)

    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            # Wczytujemy wszystkie linie, ignorując te całkowicie puste (np. spacje/entery)
            lines = [line.strip() for line in file if line.strip()]

        # Przechodzimy przez wszystkie linie w pliku
        for i in range(len(lines)):
            if block_pattern.search(lines[i]):
                # Jeśli jesteśmy w ostatniej linijce pliku i jest to blok, to siłą rzeczy jest "pusty"
                if i == len(lines) - 1:
                    orphan_count += 1
                else:
                    # Sprawdzamy, czy NASTĘPNA linia również zaczyna się od deklaracji bloku
                    if block_pattern.search(lines[i+1]):
                        orphan_count += 1

        return orphan_count

    except FileNotFoundError:
        print(f"Błąd: Nie znaleziono pliku -> {file_path}")
        return None
    except Exception as e:
        print(f"Błąd podczas przetwarzania {file_path}: {e}")
        return None

# =====================================================================
# SŁOWNIK ZE ŚCIEŻKAMI
# Wprowadź pełne, absolutne ścieżki do plików bez żadnych prefiksów.
# =====================================================================
files_data = {
    "SPHINCS+": {
        "500 tx": {
            500: r"/content/anomalia_sphincs_500tx_4MB_N500.txt",
            1000: r"/content/anomalia_sphincs_500tx_4MB_N1000.txt",
            1500: r"/content/anomalia_sphincs_500tx_4MB_N1500.txt",
            2000: r"/content/anomalia_sphincs_500tx_4MB_N2000.txt",
            4000: r"/content/anomalia_sphincs_500tx_4MB_N4000.txt"
        },
        "1000 tx": {
            500: r"/content/anomalia_sphincs_1000tx_8MB_N500.txt",
            1000: r"/content/anomalia_sphincs_1000tx_8MB_N1000.txt",
            1500: r"/content/anomalia_sphincs_1000tx_8MB_N1500.txt",
            2000: r"/content/anomalia_sphincs_1000tx_8MB_N2000.txt",
            4000: r"/content/anomalia_sphincs_1000tx_8MB_N4000.txt"
        },
        "1500 tx": {
            500: r"/content/anomalia_sphincs_1500tx_12MB_N500.txt",
            1000: r"/content/anomalia_sphincs_1500tx_12MB_N1000.txt",
            1500: r"/content/anomalia_sphincs_1500tx_12MB_N1500.txt",
            2000: r"/content/anomalia_sphincs_1500tx_12MB_N2000.txt",
            4000: r"/content/anomalia_sphincs_1500tx_12MB_N4000.txt"
        },
        "2000 tx": {
            500: r"/content/anomalia_sphincs_2000tx_16MB_N500.txt",
            1000: r"/content/anomalia_sphincs_2000tx_16MB_N1000.txt",
            1500: r"/content/anomalia_sphincs_2000tx_16MB_N1500.txt",
            2000: r"/content/anomalia_sphincs_2000tx_16MB_N2000.txt",
            4000: r"/content/anomalia_sphincs_2000tx_16MBSphincs_N4000.txt"
        }
    },
    "ECDSA (secp256k1)": {
        "500 tx": {
            500: r"/content/standard_ecdsa_500tx_N500.txt",
            1000: r"/content/standard_ecdsa_500tx_N1000.txt",
            1500: r"/content/standard_ecdsa_500tx_N1500.txt",
            2000: r"/content/standard_ecdsa_500tx_N2000.txt",
            4000: r"/content/standard_ecdsa_500tx_N4000.txt"
        },
        "1000 tx": {
            500: r"/content/standard_ecdsa_1000tx_N500.txt",
            1000: r"/content/standard_ecdsa_1000tx_N1000.txt",
            1500: r"/content/standard_ecdsa_1000tx_N1500.txt",
            2000: r"/content/standard_ecdsa_1000tx_N2000.txt",
            4000: r"/content/standard_ecdsa_1000tx_N4000.txt"
        },
        "1500 tx": {
            500: r"/content/standard_ecdsa_1500tx_N500.txt",
            1000: r"/content/standard_ecdsa_1500tx_N1000.txt",
            1500: r"/content/standard_ecdsa_1500tx_N1500.txt",
            2000: r"/content/standard_ecdsa_1500tx_N2000.txt",
            4000: r"/content/standard_ecdsa_1500tx_N4000.txt"
        },
        "2000 tx": {
            500: r"/content/standard_ecdsa_2000tx_N500.txt",
            1000: r"/content/standard_ecdsa_2000tx_N1000.txt",
            1500: r"/content/standard_ecdsa_2000tx_N1500.txt",
            2000: r"/content/standard_ecdsa_2000tx_N2000.txt",
            4000: r"/content/standard_ecdsa_2000tx_N4000.txt"
        }
},
     "Dilithium2": {
        "500 tx": {
            500: r"/content/sample_data/anomalia_dilithium2_500tx_N500.txt",
            1000: r"/content/sample_data/anomalia_dilithium2_500tx_N1000.txt",
            1500: r"/content/sample_data/anomalia_dilithium2_500tx_N1500.txt",
            2000: r"/content/sample_data/anomalia_dilithium2_500tx_N2000.txt",
            4000: r"/content/sample_data/anomalia_dilithium2_500tx_N4000.txt"
        },
        "1000 tx": {
            500: r"/content/sample_data/anomalia_dilithium2_1000tx_N500.txt",
            1000: r"/content/sample_data/anomalia_dilithium2_1000tx_N1000.txt",
            1500: r"/content/sample_data/anomalia_dilithium2_1000tx_N1500.txt",
            2000: r"/content/sample_data/anomalia_dilithium2_1000tx_N2000.txt",
            4000: r"/content/sample_data/anomalia_dilithium2_1000tx_N4000.txt"
        },
        "1500 tx": {
            500: r"/content/sample_data/anomalia_dilithium2_1500tx_N500.txt",
            1000: r"/content/sample_data/anomalia_dilithium2_1500tx_N1000.txt",
            1500: r"/content/sample_data/anomalia_dilithium2_1500tx_N1500.txt",
            2000: r"/content/sample_data/anomalia_dilithium2_1500tx_N2000.txt",
            4000: r"/content/sample_data/anomalia_dilithium2_1500tx_N4000.txt"
        },
        "2000 tx": {
            500: r"/content/sample_data/anomalia_dilithium2_2000tx_N500.txt",
            1000: r"/content/sample_data/anomalia_dilithium2_2000tx_N1000.txt",
            1500: r"/content/sample_data/anomalia_dilithium2_2000tx_N1500.txt",
            2000: r"/content/sample_data/anomalia_dilithium2_2000tx_N2000.txt",
            4000: r"/content/sample_data/anomalia_dilithium2_2000tx_N4000.txt"
        }
}
}
# =====================================================================
# GENEROWANIE WYKRESÓW
# =====================================================================
for algo_name, tx_groups in files_data.items():
    plt.figure(figsize=(10, 6))

    # Różne znaczniki na wykresie dla każdej linii
    markers = ['o', 's', '^', 'd']

    for (tx_label, nodes_dict), marker in zip(tx_groups.items(), markers):
        x_nodes = []
        y_orphans = []

        for n_size in sorted(nodes_dict.keys()):
            path = nodes_dict[n_size]
            orphans_count = calculate_orphan_blocks(path)

            if orphans_count is not None:
                x_nodes.append(n_size)
                y_orphans.append(orphans_count)

        if x_nodes and y_orphans:
            plt.plot(x_nodes, y_orphans, marker=marker, linewidth=2, markersize=8, label=f"Obciążenie: {tx_label}")

    plt.title(f"Liczba pustych/osieroconych bloków dla {algo_name}", fontsize=14, fontweight='bold')
    plt.xlabel("Rozmiar sieci (N)", fontsize=12)
    plt.ylabel("Liczba pustych bloków", fontsize=12)
    plt.xticks([500, 1000, 1500, 2000, 4000])
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.legend(title="Transakcje w bloku", fontsize=10)
    plt.tight_layout()

    plt.show()