# -*- coding: utf-8 -*-
"""testy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kupW85d7Nbm4m9ssMdCVbuWm6d5LZOqf
"""

import pandas as pd
import matplotlib.pyplot as plt
import re

def parse_simblock_log_to_sec(filename):
    """Parsuje logi SimBlock i oblicza średni czas propagacji w sekundach."""
    max_delays = []

    with open(filename, 'r') as f:
        content = f.read()

    # Szukamy bloków danych (regex dopasowany do Twoich logów)
    blocks = re.findall(r'simblock\.block\.ProofOfWorkBlock@.*:\d+\n(.*?)\n\n', content, re.DOTALL)

    for block in blocks:
        timestamps = []
        for line in block.strip().split('\n'):
            parts = line.split(',')
            if len(parts) == 2:
                timestamps.append(int(parts[1]))

        if timestamps:
            # Czas propagacji w ms -> zmiana na sekundy (/ 1000.0)
            delay_sec = (max(timestamps) - min(timestamps)) / 1000.0
            max_delays.append(delay_sec)

    return sum(max_delays) / len(max_delays) if max_delays else 0

# 1. Pliki wejściowe
files = {
    '10 Nodes': '/content/sample_data/log_10Nodes_network_1MB.txt',
    '50 Nodes': '/content/sample_data/log_50Nodes_network_1MB.txt',
    '100 Nodes': '/content/sample_data/log_100Nodes_network_1MB.txt',
    '200 Nodes': '/content/sample_data/log_200Nodes_network_1MB.txt',
    '500 Nodes': '/content/sample_data/log_500Nodes_network_1MB.txt',
    '1000 Nodes': '/content/sample_data/log_1000Nodes_network_1MB.txt',
    '2000 Nodes': '/content/sample_data/log_2000Nodes_network_1MB.txt',
    '4000 Nodes': '/content/sample_data/log_4000Nodes_network_1MB.txt'
}

results = []

# 2. Przetwarzanie i konwersja
for label, filename in files.items():
    try:
        avg_delay_sec = parse_simblock_log_to_sec(filename)
        results.append({'Konfiguracja': label, 'Czas_Propagacji_s': round(avg_delay_sec, 3)})
        print(f"Przetworzono {filename}: {avg_delay_sec:.3f} s")
    except FileNotFoundError:
        print(f"Błąd: Nie znaleziono pliku {filename}")

# 3. DataFrame
df = pd.DataFrame(results)

# 4. Wykres w sekundach
plt.figure(figsize=(10, 6))
colors = ['#3498db', '#e67e22', '#e74c3c'] # Niebieski, Pomarańczowy, Czerwony
bars = plt.bar(df['Konfiguracja'], df['Czas_Propagacji_s'], color=colors, alpha=0.8)

# Dodanie etykiet nad słupkami
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.05, f"{yval} s", ha='center', va='bottom', fontweight='bold')

plt.title('Analiza Skalowalności Blockchain: Czas propagacji (Ed25519 Klasyczny)', fontsize=14)
plt.xlabel('Rozmiar Bloku (Narzut PQC = 1MB)', fontsize=12)
plt.ylabel('Średni czas pełnej propagacji [s]', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.5)

# Zapis wykresu
plt.savefig('analiza_propagacji_Klasyczny.png')

# 5. Eksport danych
df.to_csv('wyniki_skalowalnosci_Klasyczny.csv', index=False)

# DODATEK: Tabela w formacie LaTeX (do pracy dyplomowej)
print("\n--- KOD DO LATEXA ---")
print(df.to_latex(index=False, caption="Porównanie czasu propagacji dla różnych rozmiarów bloków PQC", label="tab:pqc_propagation"))
plt.tight_layout()
plt.show()