# -*- coding: utf-8 -*-
"""Anomalia_Sphincs_500tx.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13sK4FChN7NC2UgF3ScQ03OYDW0jtenDo
"""

import os
import statistics

# Lista Twoich konkretnych plików dla algorytmu ECDSA
pliki_ecdsa = [
    "/content/anomalia_sphincs_500tx_4MB_N500.txt",
    "/content/anomalia_sphincs_500tx_4MB_N1000.txt",
    "/content/anomalia_sphincs_500tx_4MB_N1500.txt",
    "/content/anomalia_sphincs_500tx_4MB_N2000.txt",
    "/content/anomalia_sphincs_500tx_4MB_N4000.txt"
]

for pelna_sciezka in pliki_ecdsa:
    nazwa_pliku = os.path.basename(pelna_sciezka)

    print("\n" + "="*80)
    print(f"ANALIZA PLIKU: {nazwa_pliku}")
    print("="*80)

    if not os.path.exists(pelna_sciezka):
        print(f"BŁĄD: Plik nie istnieje w ścieżce: {pelna_sciezka}")
        continue

    czasy_propagacji = []
    aktualny_czas_max = 0
    licznik_blokow = 0

    with open(pelna_sciezka, 'r', encoding='utf-8') as f:
        for linia in f:
            linia = linia.strip()
            if linia.startswith("simblock.block.ProofOfWorkBlock"):
                if aktualny_czas_max > 0:
                    czasy_propagacji.append(aktualny_czas_max)
                aktualny_czas_max = 0
                licznik_blokow += 1
            elif "," in linia:
                try:
                    _, czas_str = linia.split(",")
                    czas = int(czas_str)
                    if czas > aktualny_czas_max:
                        aktualny_czas_max = czas
                except ValueError:
                    pass

        if aktualny_czas_max > 0:
            czasy_propagacji.append(aktualny_czas_max)

    # Wyświetlanie tabeli dla pojedynczego pliku
    if licznik_blokow > 0:
      # PRZELICZENIE NA SEKUNDY:
        mean_s = statistics.mean(czasy_propagacji) / 1000.0
        std_s = statistics.stdev(czasy_propagacji) / 1000.0 if licznik_blokow > 1 else 0.0
        min_s = min(czasy_propagacji) / 1000.0
        max_s = max(czasy_propagacji) / 1000.0

        print(f"{'Metryka':<15} | {'Wartość'}")
        print("-" * 30)
        print(f"{'Liczba bloków':<15} | {licznik_blokow}")
        print(f"{'Mean (s)':<15} | {mean_s:.3f}") # :.3f oznacza 3 miejsca po przecinku
        print(f"{'Std (s)':<15} | {std_s:.3f}")
        print(f"{'Min (s)':<15} | {min_s:.3f}")
        print(f"{'Max (s)':<15} | {max_s:.3f}")
    else:
        print("Brak danych propagacji w tym pliku.")

    print("="*80 + "\n")